# Configurações gerais
USUARIO="operador"
HOSTNAME_NOVO="workstation"

# Rede
CONFIGURAR_IP=false
INTERFACE_REDE="enp0s3"
TIPO_IP="dhcp"   # dhcp ou static

IP_ADDRESS="192.168.0.10"
NETMASK="255.255.255.0"
NETWORK="192.168.0.0"
BROADCAST="192.168.0.255"
GATEWAY="192.168.0.1"
# Adicionais para convidados
INSTALAR_GUEST_ADDITIONS=true


# Navegadores e programas opcionais
INSTALAR_CHROME=true
INSTALAR_OPERA=true
INSTALAR_PACKET_TRACER=false

# Pyenv / Python
INSTALAR_PYTHON_COM_PYENV=false
PYTHON_VERSION="3.13.1"

# GRUB
CONFIGURAR_GRUB=false
GRUB_BACKGROUND_IMAGE="/boot/grub/wpgrub.jpg"

# Fontes Windows
# Copie fontes opcionais para: assets/fonts/
INSTALAR_FONTES_ASSETS=false

# Packet Tracer
# Coloque o .deb em assets/packettracer/ se desejar instalar manualmente pelo script
PACKET_TRACER_DEB=""

# Opera
# Coloque o .deb em assets/opera/ se desejar instalar manualmente pelo script
# OPERA_DEB=""

#Docker Engine e Docker Desktop
INSTALAR_DOCKER=true
INSTALAR_DOCKER_DESKTOP=true

# GitHub Desktop
INSTALAR_GITHUB_DESKTOP=true

# Tela / GNOME
DESABILITAR_BLOQUEIO_TELA=true

# Extensões do Visual Studio Code
INSTALAR_EXTENSOES_VSCODE=true

#GNOME
CONFIGURAR_FAVORITOS_GNOME=true
